# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cache_decision_pb2 as cache__decision__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cache_decision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DecisionServiceStub(object):
    """DecisionService is the ML admission/TTL decision service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Decide = channel.unary_unary(
                '/cachepilot.decision.v1.DecisionService/Decide',
                request_serializer=cache__decision__pb2.DecisionRequest.SerializeToString,
                response_deserializer=cache__decision__pb2.DecisionResponse.FromString,
                _registered_method=True)


class DecisionServiceServicer(object):
    """DecisionService is the ML admission/TTL decision service.
    """

    def Decide(self, request, context):
        """Decide returns an admission and TTL decision for a single
        cache-miss.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=cache__decision__pb2.DecisionRequest.FromString,
                    response_serializer=cache__decision__pb2.DecisionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cachepilot.decision.v1.DecisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cachepilot.decision.v1.DecisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DecisionService(object):
    """DecisionService is the ML admission/TTL decision service.
    """

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cachepilot.decision.v1.DecisionService/Decide',
            cache__decision__pb2.DecisionRequest.SerializeToString,
            cache__decision__pb2.DecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)