# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cache_decision.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'cache_decision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x61\x63he_decision.proto\x12\x16\x63\x61\x63hepilot.decision.v1\"\xab\x01\n\x0f\x44\x65\x63isionRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x16\n\x0e\x66requency_1min\x18\x02 \x01(\x05\x12\x16\n\x0e\x66requency_5min\x18\x03 \x01(\x05\x12\x13\n\x0brecency_sec\x18\x04 \x01(\x01\x12\x19\n\x11inter_arrival_avg\x18\x05 \x01(\x01\x12\x17\n\x0fpayload_size_kb\x18\x06 \x01(\x01\x12\x12\n\nquery_type\x18\x07 \x01(\t\"A\n\x10\x44\x65\x63isionResponse\x12\r\n\x05\x61\x64mit\x18\x01 \x01(\x08\x12\x0e\n\x06ttl_ms\x18\x02 \x01(\x03\x12\x0e\n\x06source\x18\x03 \x01(\t2n\n\x0f\x44\x65\x63isionService\x12[\n\x06\x44\x65\x63ide\x12\'.cachepilot.decision.v1.DecisionRequest\x1a(.cachepilot.decision.v1.DecisionResponseBKZIgithub.com/shayanHadad/cachepilot/internal/mlclient/decisionpb;decisionpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_decision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZIgithub.com/shayanHadad/cachepilot/internal/mlclient/decisionpb;decisionpb'
  _globals['_DECISIONREQUEST']._serialized_start=49
  _globals['_DECISIONREQUEST']._serialized_end=220
  _globals['_DECISIONRESPONSE']._serialized_start=222
  _globals['_DECISIONRESPONSE']._serialized_end=287
  _globals['_DECISIONSERVICE']._serialized_start=289
  _globals['_DECISIONSERVICE']._serialized_end=399
# @@protoc_insertion_point(module_scope)