// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: cache_decision.proto

package decisionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DecisionRequest carries the time-windowed and document-derived
// features for one cache-miss.
type DecisionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is the post's hex-encoded MongoDB _id.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// frequency_1min is the number of times this key was accessed in
	// the last minute.
	Frequency_1Min int32 `protobuf:"varint,2,opt,name=frequency_1min,json=frequency1min,proto3" json:"frequency_1min,omitempty"`
	// frequency_5min is the number of times this key was accessed in
	// the last five minutes.
	Frequency_5Min int32 `protobuf:"varint,3,opt,name=frequency_5min,json=frequency5min,proto3" json:"frequency_5min,omitempty"`
	// recency_sec is the time in seconds since the previous access to
	// this key.
	RecencySec      float64 `protobuf:"fixed64,4,opt,name=recency_sec,json=recencySec,proto3" json:"recency_sec,omitempty"`
	InterArrivalAvg float64 `protobuf:"fixed64,5,opt,name=inter_arrival_avg,json=interArrivalAvg,proto3" json:"inter_arrival_avg,omitempty"`
	// payload_size_kb is the size of the post's media payload; 0 for
	// text-only posts.
	PayloadSizeKb float64 `protobuf:"fixed64,6,opt,name=payload_size_kb,json=payloadSizeKb,proto3" json:"payload_size_kb,omitempty"`
	// query_type is "text_post" or "media_post".
	QueryType     string `protobuf:"bytes,7,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	mi := &file_cache_decision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_decision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_cache_decision_proto_rawDescGZIP(), []int{0}
}

func (x *DecisionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DecisionRequest) GetFrequency_1Min() int32 {
	if x != nil {
		return x.Frequency_1Min
	}
	return 0
}

func (x *DecisionRequest) GetFrequency_5Min() int32 {
	if x != nil {
		return x.Frequency_5Min
	}
	return 0
}

func (x *DecisionRequest) GetRecencySec() float64 {
	if x != nil {
		return x.RecencySec
	}
	return 0
}

func (x *DecisionRequest) GetInterArrivalAvg() float64 {
	if x != nil {
		return x.InterArrivalAvg
	}
	return 0
}

func (x *DecisionRequest) GetPayloadSizeKb() float64 {
	if x != nil {
		return x.PayloadSizeKb
	}
	return 0
}

func (x *DecisionRequest) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

// DecisionResponse carries the ML service's admission decision for
// one cache-miss.
type DecisionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// admit indicates whether the Go service should cache this value.
	Admit bool `protobuf:"varint,1,opt,name=admit,proto3" json:"admit,omitempty"`
	// ttl_ms is how long, in milliseconds, the cached value should be
	// considered valid, if admit is true.
	TtlMs int64 `protobuf:"varint,2,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	// source identifies what produced this decision.
	Source        string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	mi := &file_cache_decision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_decision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_cache_decision_proto_rawDescGZIP(), []int{1}
}

func (x *DecisionResponse) GetAdmit() bool {
	if x != nil {
		return x.Admit
	}
	return false
}

func (x *DecisionResponse) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *DecisionResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_cache_decision_proto protoreflect.FileDescriptor

const file_cache_decision_proto_rawDesc = "" +
	"\n" +
	"\x14cache_decision.proto\x12\x16cachepilot.decision.v1\"\x85\x02\n" +
	"\x0fDecisionRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x0efrequency_1min\x18\x02 \x01(\x05R\rfrequency1min\x12%\n" +
	"\x0efrequency_5min\x18\x03 \x01(\x05R\rfrequency5min\x12\x1f\n" +
	"\vrecency_sec\x18\x04 \x01(\x01R\n" +
	"recencySec\x12*\n" +
	"\x11inter_arrival_avg\x18\x05 \x01(\x01R\x0finterArrivalAvg\x12&\n" +
	"\x0fpayload_size_kb\x18\x06 \x01(\x01R\rpayloadSizeKb\x12\x1d\n" +
	"\n" +
	"query_type\x18\a \x01(\tR\tqueryType\"W\n" +
	"\x10DecisionResponse\x12\x14\n" +
	"\x05admit\x18\x01 \x01(\bR\x05admit\x12\x15\n" +
	"\x06ttl_ms\x18\x02 \x01(\x03R\x05ttlMs\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source2n\n" +
	"\x0fDecisionService\x12[\n" +
	"\x06Decide\x12'.cachepilot.decision.v1.DecisionRequest\x1a(.cachepilot.decision.v1.DecisionResponseBKZIgithub.com/shayanHadad/cachepilot/internal/mlclient/decisionpb;decisionpbb\x06proto3"

var (
	file_cache_decision_proto_rawDescOnce sync.Once
	file_cache_decision_proto_rawDescData []byte
)

func file_cache_decision_proto_rawDescGZIP() []byte {
	file_cache_decision_proto_rawDescOnce.Do(func() {
		file_cache_decision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_decision_proto_rawDesc), len(file_cache_decision_proto_rawDesc)))
	})
	return file_cache_decision_proto_rawDescData
}

var file_cache_decision_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cache_decision_proto_goTypes = []any{
	(*DecisionRequest)(nil),  // 0: cachepilot.decision.v1.DecisionRequest
	(*DecisionResponse)(nil), // 1: cachepilot.decision.v1.DecisionResponse
}
var file_cache_decision_proto_depIdxs = []int32{
	0, // 0: cachepilot.decision.v1.DecisionService.Decide:input_type -> cachepilot.decision.v1.DecisionRequest
	1, // 1: cachepilot.decision.v1.DecisionService.Decide:output_type -> cachepilot.decision.v1.DecisionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cache_decision_proto_init() }
func file_cache_decision_proto_init() {
	if File_cache_decision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_decision_proto_rawDesc), len(file_cache_decision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_decision_proto_goTypes,
		DependencyIndexes: file_cache_decision_proto_depIdxs,
		MessageInfos:      file_cache_decision_proto_msgTypes,
	}.Build()
	File_cache_decision_proto = out.File
	file_cache_decision_proto_goTypes = nil
	file_cache_decision_proto_depIdxs = nil
}
